# Generated by Django 3.2.7 on 2021-09-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mafhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MafFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entry', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('maf_file', models.FileField(max_length=300, upload_to='desktop')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafhandler.account', verbose_name='username')),
            ],
        ),
    ]
