# Generated by Django 3.2.7 on 2021-09-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafhandler', '0003_auto_20210909_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maffile',
            name='maf_file',
            field=models.FileField(max_length=300, upload_to='desktop/django'),
        ),
    ]
