# Generated by Django 3.2.7 on 2021-09-16 12:40

import django.core.validators
from django.db import migrations, models
import mafhandler.models


class Migration(migrations.Migration):

    dependencies = [
        ('mafhandler', '0013_alter_maffile_maf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maffile',
            name='maf_file',
            field=models.FileField(max_length=300, null=True, unique=True, upload_to=mafhandler.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'tsv'])]),
        ),
    ]
